### PR TITLE
Complete porting of documentation to Sphinx

### PR DESCRIPTION
**Pull request by hiperiondev**

### CODE REVIEW

**Comment by skiars** [comment]
image

The description in the note seems to be in Return.

**Comment by hiperiondev** [comment]
Berry.h must be completed. A lot of missing functions documentation.
The problem in api documentation Is about theme of sphinx, not separate note from description, it's not a problem of doxygen. Will be solved in the next work, when I'll add new theme.

**Comment by skiars** [comment]
All right!

**Review by skiars — APPROVED** [review]

**Comment by s-hadinger** [comment]
@hiperiondev Are you still there? I'm trying to sync between the wiji and readthedocs, but I don't find any simple way. Nor how to automate the generation of documentation.

**Pull request merged**
