### PR TITLE
Bytes add string

### PR DESCRIPTION
**Pull request by s-hadinger**
Allow `bytes()` to add a `string`:

```berry
b = bytes()
b .. 'hello'
print(b)
# bytes('68656C6C6F')
```

### CODE REVIEW

**Comment by skiars** [comment]
I think using `..` for semantics like `+=` is not too good, the `append()` method might be better? `..` or `+` should not modify the operands?

**Comment by s-hadinger** [comment]
I didn't like too much `..` in the first place but it was already there for strings and lists. I don't think it's harming to add it here, although I will add `append` as an alternative. 

`+=` does create a new object which defeats the purpose. 

To add some color, I'm adding ways to manipulate bytes without allocating new objects and without adding pressure on the garbage collector. This was to implement an async web server that sends data every 100ms. Hence the gc would have a lot of work without these tricks

**Comment by s-hadinger** [comment]
I made the change to add `append()`

**Comment by s-hadinger** [comment]
@skiars There multiple open PRs that I can't merge unless you approve them. 

Would you be kind enough to approve them?

**Review by skiars — APPROVED** [review]

**Comment by skiars** [comment]
Done.

**Pull request merged**
