### PR TITLE
Pycoc

### PR DESCRIPTION
**Pull request by s-hadinger**
This is a big one. Last week I ported `coc` compiler to Python3 which will make it easier to do it in CI within Tasmota. I checked the `pycoc` compiler that outputs exactly the same bytes as `coc` compiler.

Then I changed the string encoding to make it easier to onboard solidified strings. Now `be_const_str_<XXX>` is now encoded in a bijection system, so that the pycoc parser can recreate the original string from the indetifier.

Encoding:
- `_X` is used as a marker for espace
- `A-Za-z0-9` are unchanged
- `_X` is replaced with `_X_`, any other occurence of `_` is unchangedd
- any other char is replaced with `_XHH` where `HH` is the hex of the character

Example:
- `"_upper_"` becomes `be_const_str___upper__`
- `".."` becomes `be_const_str__X3D_X3D`
- `".p"` becomes `be_const_str__X2Ep`

### CODE REVIEW

**Comment by skiars** [comment]
Are you planning to remove C++ coc? Maintaining both implementations should be very troublesome.

**Comment by s-hadinger** [comment]
No, I don't. But I found it a little rude to remove your C++ code and wanted your opinion first.

**Comment by skiars** [comment]
Thanks! There is no problem.

**Comment by skiars** [comment]
Will the performance of the python version be much worse? I have compiled Berry on the ARM platform (very very slow).

**Comment by s-hadinger** [comment]
Wow. Speed was clearly not my focus. RAM usage might be an issue too (but C++ version as well) since all source code files are loaded in RAM first, and strings are allocated per source file before being joined in the final structure.

For Tasmota with lots of big source files, it takes 0.33s on a 2018 mac.

**Comment by s-hadinger** [comment]
I can see the warning on your ARM saying `int` and `void*` having different sizes. Are you compiling with 64 bits int? In such situation will `introspect` not behave well.

**Comment by skiars** [comment]
I used 64bit `bint`.

Source files should be read one by one, not all of them should be read into memory. In fact, there are very few valid source codes for coc in the entire project, so the RAM usage may not be large.

On the other hand, every time make seems to call coc to scan the entire project, which will slow down every compilation. This may be a future optimization point (I don't like slow compilation).

**Comment by s-hadinger** [comment]
0.3s is not what I call slow ;)

Indeed, files are only loaded one by one, and the lines of interest for coc are found with Python's native regex engine.

The regex pattern is derived from `coc_parser.parsers` and its value is `"@const_object_info_begin|be_const_str_|be_const_key(|be_nested_str(`"

**Comment by skiars** [comment]
OK, I will merge this PR. Maybe the C++ coc can be removed later.

**Pull request merged**
